### ISSUE TITLE
document or detect non standard ports for graphql, grpc, rest and websockets

### ISSUE THREAD

**Issue by alexeadem** [wallarm/gotestwaf#104]
grpc and graphql is not working in my environment although gRPC is listening on port 3.83.89.253:8081 and graphql on port 3.83.89.253:9443. What are the default ports we are scanning graphql, gRPC on (maybe we should documents this)? And is there a way to scan custom ports for specific APIs?

**Comment by svkirillov** [comment]
Hi!

We recently added a new CLI option to specify the gRPC server port. Now you can specify the port on which the gRPC server is listening with the `--grpcPort` option. Note that the url will be the same. Unfortunately GraphQL is not yet supported as a separate protocol.
