### ISSUE TITLE
Tool is not working on the new Mac Chips

### ISSUE THREAD

**Issue by daknhh** [wallarm/gotestwaf#114]
Digest: sha256:d1d7bcfccfde963af096bb57690b95120f076beb08c00336a21f001390cce2c8
Status: Downloaded newer image for wallarm/gotestwaf:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Hardware informations:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	64 GB

**Comment by adrianbumbas** [comment]
I have a Mac M1 and it works, just use `--verbose` to see what exactly is going on.

**Comment by daknhh** [comment]
I will check tomorrow 🙏
