### ISSUE TITLE
test case not completing waiting at last test

### ISSUE THREAD

**Issue by MubasheerSiddiqui** [wallarm/gotestwaf#116]
main.go:173: main: interrupt : scan canceled
GOTESTWAF : 2022/02/02 13:31:50.263639 scanner.go:291: http sending: sending http request: Post "http://localhost:4300": context canceled
GOTESTWAF : 2022/02/02 13:31:50.263741 scanner.go:201: Scanning Time:  348ns
GOTESTWAF : 2022/02/02 13:31:50.263772 scanner.go:201: Scanning finished
GOTESTWAF : 2022/02/02 13:31:50.263800 main.go:46: main error: run scanning: context canceled

waited for 30 min but nothing happend
![image](https://user-images.githubusercontent.com/60107503/152164475-6d0741d9-0bb3-425a-81a0-8d052276b4bf.png)
server is simple express server

const express = require('express');
const app = express();
const port = 4300;

app.get("/", (req, res) => {
    console.log("In Get Req");
    console.log("Header " + JSON.stringify(req.headers));
    console.log("Body " + JSON.stringify(req.body));

    res.status(200).send("Hello");
})
app.post("/", (req, res) => {
    console.log("In Post Req");
    console.log("Header " + JSON.stringify(req.headers));
    console.log("Body " + JSON.stringify(req.body));
    res.status(200).send()
})

app.listen(port, () => {
    console.log("Server Started on Port: " + port);
})

**Comment by svkirillov** [comment]
Hi!

Sorry, but I couldn't reproduce this error.
