### ISSUE TITLE
POST request template config file

### ISSUE THREAD

**Issue by ronoski** [wallarm/gotestwaf#118]
Can you give an example of template config.yaml file with POST request?

something like:
POST /api/login

{"email":"test@mail.com","password":"test"}

**Comment by svkirillov** [comment]
Hi!

Sorry, but in the current version of GoTestWAF, there is no way to create POST requests with a user-defined body. Headers, request parameters, and body structures have randomly generated names and predefined structures (for JSONRequest and SOAPBody).
