### ISSUE TITLE
Adding folder and creating custom test cases

### ISSUE THREAD

**Issue by s1nglethr3ad** [wallarm/gotestwaf#121]
I created a folder under testcases and added my custom.yml file.  Using the docker run command with --testSet produces an error.

GOTESTWAF : 2022/03/22 17:00:57.943406 main.go:46: main error: loading test case: no tests were selected

I have tried various methods to get a custom test case to run with no success.

Is there documentation for adding custom test cases to the tool?

Command with errors:
docker run -v ${PWD}/reports:/app/reports wallarm/gotestwaf --url=http://192.168.1.4 --testSet custom-urls --verbose

Command that works:
docker run -v ${PWD}/reports:/app/reports wallarm/gotestwaf --url=http://192.168.1.4 --testSet community --verbose

The tool will read in the yml files from the community folder.  It will not read in custom.yml from my folder custom-urls.

Thanks!

**Comment by svkirillov** [comment]
Hi!

You can easily add new test sets to existing ones via docker volume. For example, if you have a directory with custom yaml files located at `/full/path/to/custom-urls`, you can use it for testing in the following way:
```shell
docker run -v ${PWD}/reports:/app/reports -v /full/path/to/custom-urls:/app/testcases/custom-urls wallarm/gotestwaf --url=http://192.168.1.4/ --testSet custom-urls --verbose
```

In general any directory with yaml files must have the following structure:
`.../<test cases path>/<test set name>/<test case name>.yml`

If you have several test sets (e.g. `set1`, `set2`, ...), you cat put them in one directory (e.g. `my-tests`) and use it to test your product:
```shell
docker run -v ${PWD}/reports:/app/reports -v /full/path/to/my-tests:/app/my-tests wallarm/gotestwaf --url=http://192.168.1.4/ --testCasesPath my-tests --verbose
```
