### ISSUE TITLE
JSON export beside  HTML/PDF report

### ISSUE THREAD

**Issue by 0wlyW00d** [wallarm/gotestwaf#127]
Is there a possibilities to get results in a JSON file beside ready-to-go HTML/PDF report ? 

Is it a possible feature, or already in the roadmap ?
I would like to implement the result of the tool with other tools :)

**Comment by svkirillov** [comment]
Hi!

Unfortunately, it is currently not possible to output the report in JSON format. But there are plans to implement such functionality.
