### ISSUE TITLE
Quits without any output

### ISSUE THREAD

**Issue by arcreative** [wallarm/gotestwaf#129]
I've tried running this via all the docker methods, including pulling the repo and building the image from scratch.  Does not log any output, doesn't work, doesn't put anything in reports directory... not sure what else I can do since the self-contained Docker solution isn't working.

**Comment by svkirillov** [comment]
Hi!

Are you running GoTestWAF with `--verbose` flag? Without this flag, in some cases, when an error occurs, GoTestWAF simply exits without any messages.

**Comment by arcreative** [comment]
@svkirillov Thanks, it was telling me a WAF was not detected for the domain I was testing on.  I guess initially when i tried `--verbose` it was too early in the arguments such that it was passed to Docker and not to gotestwaf.  Wondering if verbose shouldn't be the preferred default, and maybe have a `--quiet` argument instead?

**Comment by svkirillov** [comment]
Fixed in #134
