### ISSUE TITLE
addHeader can't change Host header. 

### ISSUE THREAD

**Issue by d0znpp** [wallarm/gotestwaf#132]
https://github.com/wallarm/gotestwaf/blob/fc24909aa5d5f435d20ae2493ee6066f2ce040c0/internal/scanner/http_client.go#L62

We have an issue with changing Hostname

**Comment by svkirillov** [comment]
Unfortunately we can't change this behavior because the Host header is set at the time the request is made inside the standard libraries: https://github.com/golang/go/blob/go1.18.3/src/net/http/request.go#L617

**Comment by svkirillov** [comment]
Hi! Could you please check if [this fix](https://github.com/wallarm/gotestwaf/pull/133) solves the problem for your case?
