### ISSUE TITLE
Rendering of PDF report fails

### ISSUE THREAD

**Issue by thesebastiaan** [wallarm/gotestwaf#144]
Hi, 

I'm using the Docker image on a M1 Mac to run the tests. The command line report generate fine, but the PDF does not.

The command I'm running:

docker run -v reports:/app/reports wallarm/gotestwaf --url=https://<my url>

The error:

time="2022-08-10T13:53:37Z" level=error msg="caught error in main function" error="couldn't export full report: couldn't render HTML report to PDF: signal: trace/breakpoint trap"

**Comment by thesebastiaan** [comment]
If I just check out go repo and use that, PDF reports are generated. Issues seems to be with the docker container only. Maybe related to the Docker volume mapping.

**Comment by svkirillov** [comment]
Hi! Have you tried to build a docker container from git master and try running it, or did you run it without docker?

**Comment by marianod92** [comment]
Hi!
I have the same issue when i run **_GoTestWaf_** on Docker.
When i run with Go (as script from comnand-line), the test finish successful and generate PDF reports.

**Comment by svkirillov** [comment]
@marianod92 Hi!

Have you tried to build the docker image yourself and running it? I have a suspicion that the problem is that the docker image is built only for the x86 platform. Unfortunately I don't have a M1 Mac to check my suggestion. Could you check?

**Comment by thesebastiaan** [comment]
Haven' tried to built the docker image. I will do that and report back, but will probably do it this weekend.

**Comment by marianod92** [comment]
> @marianod92 Hi!
> 
> Have you tried to build the docker image yourself and running it? I have a suspicion that the problem is that the docker image is built only for the x86 platform. Unfortunately I don't have a M1 Mac to check my suggestion. Could you check?

Hi @svkirillov 

I forgot to mention it, but I have the same suspicion as I am working with a Mac M1 and running Docker there.
I was waiting for some aw to try with some Intel Mac to reproduce the error and confirm that it is because of this. 

I am using the latest available version of the GoTestWaf Docker Image available. I did not yet build locally and ran with a build on M1.

I will try to make the build to see if that solves the error and it would be simply to add an image of this type to the registry. Right?

Thanks!

**Comment by s-demp** [comment]
Had the same problem running on my M1.

Building from the docker file and changing to arm64v8/golang:1.19-alpine fixes the problem

**Comment by svkirillov** [comment]
Hi!

We have migrated to GitHub Actions instead of webhooks to build and push images to Docker Hub. Now images are built for `linux/amd64` and `linux/arm64`. Could you please check if everything works as expected on Apple Silicon?

https://hub.docker.com/r/wallarm/gotestwaf/tags
