### ISSUE TITLE
Go package

### ISSUE THREAD

**Issue by anfokaboom** [wallarm/gotestwaf#146]
Just a question, please.

Running GoTestWAF in any capacity, for instance in Docker or just a plain instance of Kali requires the Go package, is that correct?

**Comment by svkirillov** [comment]
Hi!

Compiled go binaries are self-sufficient. You can run a pre-built standalone executable file without any additional runtime environment (except standard system libraries of course). For GTW, if you have a compiled binary to run, you will need a [config file](https://github.com/wallarm/gotestwaf/blob/master/config.yaml) and [testcases](https://github.com/wallarm/gotestwaf/tree/master/testcases). All requirements to build and run are listed [here](https://github.com/wallarm/gotestwaf#requirements).
