### ISSUE TITLE
[Feature Request] Ability to add a unique identifier for each test case

### ISSUE THREAD

**Issue by joshcampbell191** [wallarm/gotestwaf#148]
We're currently using this tool to test the effectiveness of our WAF and have run into an issue when trying to compare our logs against each other between configuration changes. Since we didn't enable (yet) the blocking mechanism on our WAF, we can't rely on the results from GoTestWAF however the WAF logs still indicates when it encounters suspicious requests.

Would it be possible to add an additional header or something containing a unique identifier (ex. a hash of the payload, placeholder, encoder and test case) for each test that can be used to map the results between the logs?

**Comment by svkirillov** [comment]
Hi!

Currently we have a fingerprint of testcases in console/pdf reports. Does this solve your problem?

**Comment by joshcampbell191** [comment]
A custom header with a hash of the payload would be preferable. Also, I didn't notice the fingerprint in the CSV results.

**Comment by svkirillov** [comment]
Hi!

We have added a new option `--addDebugHeader`, which allows you to add the hash of the current test to the request. The hash is computed as sha256 from the test set, name, placeholder, encoder and payload. You can find the hash value in the `X-GoTestWAF-Test` header value. If you have a question related to this feature, you can re-open this issue.
