### ISSUE TITLE
openapiFile -  no such file or directory

### ISSUE THREAD

**Issue by ORuessel** [wallarm/gotestwaf#149]
Good morning erveryone,

thanks for the good waf testing tools. In preparation to test waf with API Gateway on AWS i want to load a prepared openAPI Definition in version openAPI 3.0.0. 

In testcase i run the docker container with follow command to add the openapi file to the docker container testing. Based on that with full qualified folder information or with relative path i get the error message no such file or directory.

<code>
docker run -v /home/oru/:/app/reports --network="host" wallarm/gotestwaf --url=https://url/api/v1/ --openapiFile=openapidefinition.yaml
</code>

Does anyone has an idea to this topic ? Best regards and thanks for support.
Oliver

**Comment by svkirillov** [comment]
Hi!

It looks like the path to the openAPI file is wrong. You need to add another volume mount for your openAPI file to `/app`. Something like that:

```
docker run -v /home/oru/:/app/reports -v /home/oru/openapidefinition.yaml:/app/openapidefinition.yaml --network="host" wallarm/gotestwaf --url=https://url/api/v1/ --openapiFile=openapidefinition.yaml
```

**Comment by ORuessel** [comment]
Hello @svkirillov,

thanks that work as expect.
