### ISSUE TITLE
Error message : "panic: assignment to entry in nil map"

### ISSUE THREAD

**Issue by eguillotin** [wallarm/gotestwaf#154]
Hi,

I have a "panic: assignment to entry in nil map" error message in the last gotestwaf versions. 

This seems to be related to an uninitialized map, however I'm not a go expert and I don't know if my fix has a side effect on the grpc tests that I don't use, so I'll let you check.

I fixed it by initializing _counters["api"]_ in ligne 151 in the report/chart.go file : 

if !s.IsGrpcAvailable {
		// gRPC is part of the API Security tests
		**_counters["api"] = make(map[string]pair)_**
		counters["api"]["grpc"] = pair{}
	}

**Comment by svkirillov** [comment]
Hi!

Did you use your own set of testcases?

**Comment by eguillotin** [comment]
Hi, no I use the default ones but I run them one by one via  the --testSet and --testCase flags and it seemed I didn't get the error for the owasp-api testcases.

**Comment by svkirillov** [comment]
Fixed in #156
