### ISSUE TITLE
Error when trying to generate Go module

### ISSUE THREAD

**Issue by whoot** [wallarm/gotestwaf#155]
Hey, tried to build the go module, however, I am getting the following error:

```
git clone https://github.com/wallarm/gotestwaf.git
cd gotestwaf
gotestwaf> go build -mod vendor -o gotestwaf ./cmd/main.go

# command-line-arguments
cmd\main.go:47:15: undefined: parseFlags
cmd\main.go:52:5: undefined: quiet
cmd\main.go:55:18: undefined: logLevel
cmd\main.go:57:5: undefined: logFormat
cmd\main.go:57:18: undefined: jsonLogFormat
cmd\main.go:61:14: undefined: loadConfig
cmd\main.go:162:103: undefined: logFormat
```

**Comment by svkirillov** [comment]
Hi!

To properly build GoTestWAF manually, you need to specify the entire `./cmd` package:
```sh
﻿go build -mod vendor -o gotestwaf ./cmd/
```

But you can use the Makefile to build GoTestWAF binary/docker image via `make`:
```sh
# build docker image
make gotestwaf

# build executable file
make gotestwaf_bin
```

If you want to build GoTestWAF containing a version from git, you need to add additional arguments to the `go build` command:
```sh
go build -ldflags "-X github.com/wallarm/gotestwaf/internal/version.Version=$(git describe)" -o gotestwaf ./cmd
```

**Comment by whoot** [comment]
Thanks for clarification. Using the shown command worked.

Please update the Readme.md under "Other options to run GoTestWAF" -> "Clone this repository and build GoTestWAF as the Go module:" so it uses the correct command.
