### ISSUE TITLE
panic: runtime error: slice bounds out of range [-2:] on macOS 13.0

### ISSUE THREAD

**Issue by daknhh** [wallarm/gotestwaf#163]
INFO[0000] GoTestWAF started                             version=unknown
INFO[0000] Test cases loading started
panic: runtime error: slice bounds out of range [-2:]

goroutine 1 [running]:
github.com/wallarm/gotestwaf/internal/db.LoadTestCases(0xc0000a8680)
	/Users/davidkrohn/Downloads/gotestwaf-master/internal/db/load.go:36 +0x708
main.run({0x183e958, 0xc00013cc40}, 0xc00053bb20)
	/Users/davidkrohn/Downloads/gotestwaf-master/cmd/main.go:91 +0x345
main.main()
	/Users/davidkrohn/Downloads/gotestwaf-master/cmd/main.go:42 +0x20d

**Comment by svkirillov** [comment]
Hi! Could you provide the full command please?

**Comment by svkirillov** [comment]
Ok. Thanks!
