### ISSUE TITLE
gotestwaf not working against a WAF using 302 Redirect as blocked page

### ISSUE THREAD

**Issue by fa-alenoir** [wallarm/gotestwaf#165]
Hi,

I used both the latest Docker image and latest source code today against a WAF that return a **HTTP 302 Redirect** when blocking an URL (probably NetScaler)

I tried to play around the options  **--maxRedirects 0 --blockStatusCode 302**
but even with that, GTW was not able to count/recognize 302 responses as a block, so it proceeds to all the 1415 requests but at the end the reports it said 0 requests blockeds, althought there were few hundreds of 302 redirects that are related to a blocked request from the WAF.

I think the problem is that gotestwaf follow the redirection no matter what, and so the 302 response is never returned and compared

**_line 54 ||  internal/scanner/http_client.go_**
```
	redirectFunc = func(req *http.Request, via []*http.Request) error {
		if len(via) > cfg.MaxRedirects {
			return errors.New("max redirect number exceeded")
		}
		return nil
	}
```
should be replaced by something like that probably:

```
	redirectFunc = func(req *http.Request, via []*http.Request) error {
		return http.ErrUseLastResponse
	}
```

So the redirection is not followed and the 302 response is returned until the last control and compared with the provided **--blockStatusCode** parameter

Cheers ! :)

**Comment by fa-alenoir** [comment]
It seems to act the same with any HTTP Redirection, not only 302

**Comment by svkirillov** [comment]
Hi!

It looks like WAF wants to set session cookies and don't want to let you access the site without them. This leads to permanent redirections. Try to use `--followCookies` and `--renewSession` options.

**Comment by fa-alenoir** [comment]
I tried with the fix I sent to you and with that, GTW doesn't follow redirection so the 302 can be defined as a Block Status

**Comment by svkirillov** [comment]
Ok, I will fix it. Can you provide an URL I can test on?

**Comment by fa-alenoir** [comment]
Any scan on a tinyurl should do the trick, for example **https://tinyurl.com/3xvbx526** ==> www.google.fr
on this case it's an HTTP 301 Redirect, but that's exactly the same problem

**Comment by fa-alenoir** [comment]
Thanks !! I'll let you know
