### ISSUE TITLE
Nginx + ModSecurity

### ISSUE THREAD

**Issue by rubensaraiva10** [wallarm/gotestwaf#171]
Hello I was using GoTestWaf to test Nginx + ModSecurity with Paranoia Level 3 and I am getting a lot of True Positives

![image](https://user-images.githubusercontent.com/80674442/203608939-fa7ab534-cf3c-486d-8236-bd100e49a7a4.png)

**Comment by svkirillov** [comment]
Hi!

Could you please explain where the error is or why results should be different?
