### ISSUE TITLE
Unable to send report to email

### ISSUE THREAD

**Issue by drey143** [wallarm/gotestwaf#172]
Hello I'm wondering why the report is unable to be sent to my email. any help will be appreciated.thanks

~~~
ERRO[0500] caught error in main function                 error="couldn't send report by email: couldn't marshal report data into JSON format: json: unsupported value: NaN"

**Comment by svkirillov** [comment]
Hi!

Thanks for the report! This looks like a bug. I added a check for NaN floating point values to prevent this behavior.

**Comment by drey143** [comment]
Hi @svkirillov thanks for your quick response. I just tried it now and still getting same error message

**Comment by drey143** [comment]
it's strange everything is 0.00 or n/a. because the default_action in place for the WAF right now is "count"

**Comment by svkirillov** [comment]
`blockStatusCode` is equal to 20. Is it ok?

**Comment by drey143** [comment]
that was a typo..its 200

**Comment by drey143** [comment]
@svkirillov .its working now. thank you
