### ISSUE TITLE
Placeholders for useragent value and file extension in url 

### ISSUE THREAD

**Issue by falconkei** [wallarm/gotestwaf#190]
its good to have ability to write test cases for  User-agent values  and file extensions in URL

**Comment by svkirillov** [comment]
Hi!

We will add `UserAgent` placeholder in the next release (which will soon). If you want to perform tests with your own vectors, you can build GTW from [this MR](https://github.com/wallarm/gotestwaf/pull/200) and craft custom testcase file.

You can also create your own testcase file with filenames and some extensions using `Plain` encoder and `URLPath` placeholder.

**Comment by svkirillov** [comment]
In the new release (`v0.4.3`), we have added a new placeholder for substituting payloads in the `User-Agent` header (PR #200) and several vectors (PR #204).
