### ISSUE TITLE
Docker image tagging

### ISSUE THREAD

**Issue by jsonmart** [wallarm/gotestwaf#194]
Hi,

It would be great if GoTestWAF could adopt a release strategy which saw regular tagging of commits with semantic versions and saw git tags flow through to Docker image tags, as at the moment it's a bit tricky to use a recent version of GoTestWAF within a CI environment and achieve predictable results.

It looks like the Docker metadata action could  be used to achieve this: https://github.com/marketplace/actions/docker-metadata-action

Thanks for considering this request.

**Comment by svkirillov** [comment]
Hi!

Thank you for suggestion! 

Now we have a several images:
- the `edge` image contains latest changes from the `master` branch;
- `x.y.z` is an image built on the corresponding tag;
-  the `latest` image refers to the latest available tag.
