### ISSUE TITLE
Base64 enable/disable flag or static parameter names ? 

### ISSUE THREAD

**Issue by eguillotin** [wallarm/gotestwaf#197]
(Enhancement) | It would be interesting to have the ability to enable/disable base64 encoding for test cases from the command line as a number of WAF solutions perform base64 decoding on a per-parameter basis, specifying their names, which is not possible with GoTestWAf as the parameter names seem to be randomly generated at each iteration. Another option would be to be able to specify the parameter names statically.

**Comment by svkirillov** [comment]
Hi!

It seems that this will simplify the work for WAF, which will negatively affect the quality of testing. Could you please describe your case in more detail?

At least, you can remove the `Base64` encoder from all testcase files if you need a quick fix.

**Comment by eguillotin** [comment]
Hi,

The tool can mainly test WAFs that automatically detect base64 encoding (and thus also those that do not support it at all) but it cannot benchmark WAFs that only decode paths and parameters that are explicitly specified (e.g. to minimize the latency introduced by decoding or to achieve a more predictable behavior reducing the risk of false positives or negatives that can occur with automatic detection). It would therefore be interesting to be able to cover all these cases, by also allowing the use of predefined base64 encoded parameters and paths, possibly weighting the scores differently, rather than having to disable these tests.
