### ISSUE TITLE
Dealing with blockStatusCodes=200 and passStatusCodes=200

### ISSUE THREAD

**Issue by keisari-ch** [wallarm/gotestwaf#198]
Hi,

I'm trying to report against a f5 waf.

When a request is rejected with a curl :
```
 $ curl -i "https://random.com/%e5%98%8dSet-cookie%3acrlf%3dinjection"
HTTP/2 200
<html><head><title>**Request Rejected**</title></head>
<body>The requested URL was rejected. Please consult with your administrator.<br/><br/>
Your support ID is 9427b014-905b-43b4-9157-4d525e53bea5<br/><br/><a href='javascript:history.back();'>[Go Back]</a></body></html>
```

This request wont show uo on  the nginx logs of the backend server.

When i play a test with :
`./gotestwaf --skipWAFBlockCheck --testCase crlf --blockRegex="Rejected"--blockStatusCodes=200 --passRegex="Welcome" --passStatusCodes=200 --url=https://random.com/`

Everything goes Unresolved.

If i remove the pass* args, a lot of the tests goes bypassed, and i actually can see the backend nginx server logging the requests.

I find it weird the WAF solution lets gotestwaf pass and block the curl requests ? Whats the trick here ?

**Comment by keisari-ch** [comment]
Not used to PR in github, but i ll give a try with :
https://github.com/wallarm/gotestwaf/blob/master/internal/scanner/scanner.go#L366

Which seems to be a copy paste from the previous func.

**Comment by svkirillov** [comment]
Hi!

Thanks for the bugfix!

I guess you need to use only `--blockRegex='.*Rejected.*'` and `--passRegex='.*Welcome.*'`

**Comment by svkirillov** [comment]
Note that using `--blockStatusCodes=200` and `--passStatusCodes=200` at the same time will cause your requests to be marked as unresolved.
