### ISSUE TITLE
Unable to create report in 0.4.1

### ISSUE THREAD

**Issue by whatthejay** [wallarm/gotestwaf#201]
When I run gotestwaf 0.4.1, it shows error when creating report file.

Summary:
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|            TYPE             | TRUE-NEGATIVE TESTS BLOCKED | TRUE-POSITIVE TESTS PASSED  |           AVERAGE           |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
| API Security                | 11.76%                      | n/a                         | 11.76%                      |
| Application Security        | 24.52%                      | 88.36%                      | 56.44%                      |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|                                                                        SCORE            |           34.10%            |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+

Do you want to include payload details to the report? ([y/N]): y
ERRO[0268] caught error in main function                 error="couldn't export full report: couldn't render HTML report to PDF: signal: trace/breakpoint trap (core dumped)"

**Comment by svkirillov** [comment]
Hi!

Could you please provide some information about host system and running method (Docker/binary)?
