### ISSUE TITLE
Error generating report

### ISSUE THREAD

**Issue by Nikoolayy1** [wallarm/gotestwaf#214]
Hello,

This is a great tool but in the new version I see this error when I run it in pdf or html:

ummary:
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|            TYPE             | TRUE-NEGATIVE TESTS BLOCKED | TRUE-POSITIVE TESTS PASSED  |           AVERAGE           |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
| API Security                | 100.00%                     | n/a                         | 100.00%                     |
| Application Security        | 90.37%                      | 0.00%                       | 45.19%                      |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|                                                                        SCORE            |           72.60%            |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+

Do you want to include payload details to the report? ([y/N]): time="2023-08-01T17:53:22Z" level=error msg="caught error in main function" error="couldn't export full report: couldn't export report to HTML: rename /tmp/gotestwaf_report_3024506283.html reports/waf-evaluation-report-2023-August-01-17-53-22.html: invalid cross-device link"
                                                                                                                                   

I switched some options but the same

docker run -it --network="host" wallarm/gotestwaf --url=https://xxxx/ --blockStatusCodes=403 --reportFormat=html --noEmailReport

Summary:
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|            TYPE             | TRUE-NEGATIVE TESTS BLOCKED | TRUE-POSITIVE TESTS PASSED  |           AVERAGE           |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
| API Security                | 100.00%                     | n/a                         | 100.00%                     |
| Application Security        | 90.37%                      | 0.00%                       | 45.19%                      |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|                                                                        SCORE            |           72.60%            |
+-----------------------------+-----------------------------+-----------------------------+-----------------------------+

ERRO[0410] caught error in main function                 error="couldn't export full report: couldn't export report to HTML: rename /tmp/gotestwaf_report_3683717233.html reports/waf-evaluation-report-2023-August-01-18-22-14.html: invalid cross-device link"

**Comment by svkirillov** [comment]
Hi!

Could you please provide information about the host system and docker?

**Comment by Nikoolayy1** [comment]
Hello,

Docker container in a VM (Vmware Player/workstation) that is Kali Linux.
