### ISSUE TITLE
Using flag ignoreUnresolved, false positive unresolved testcases are considered as blocked 

### ISSUE THREAD

**Issue by falconkei** [wallarm/gotestwaf#217]
When using the ignoreUnresolved flag to true,  usual unresolved testcases are considered as bypassed but the false-positive test cases are considered as blocked. I think unresolved false positive testcases should also be considered a bypassed

**Comment by svkirillov** [comment]
Hi!

This is fine. For "true negative" tests, the WAF is expected to block the payload, and when using the ignoreUnresolved flag, we mark unresolved test cases as bypassed. But for a "false positive" tests the situation is completely opposite. We expect the payload not to be blocked by the WAF, so when we use the ignoreUnresolved flag, we mark unresolved test cases as blocked.
