### ISSUE TITLE
Clarification of report interpretation ?

### ISSUE THREAD

**Issue by eguillotin** [wallarm/gotestwaf#221]
At the beginning of the reports (pdf, html) we have a summary section with two columns named “true negative test blocked” (False Positives) and “true positive test passed” (False Negatives). Given the percentages displayed, shouldn't the names of these columns be labelled "true-positive tests blocked" and "true-negative tests passed" or can you explain how to interpret it ?

**Comment by svkirillov** [comment]
Hi!

Thanks for feedback. This is really a bug. We have fixed it in the latest version - v0.4.10.
