### ISSUE TITLE
Unable to export report using the latest docker image

### ISSUE THREAD

**Issue by Utkarsh2104** [wallarm/gotestwaf#248]
Error -> caught error in main function" error="couldn't export full report: couldn't render HTML report to PDF: couldn't render HTML file to PDF: chrome failed to start:\nFailed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted. 
Using the previous image, it was working fine.

**Comment by svkirillov** [comment]
Hi!

Thanks for the report. Could you please provide the full GTW run command and information about the environment?

**Comment by svkirillov** [comment]
Fixed in version v0.5.2. Note that if you want to use Chrome as a client to perform HTTP requests (via the `--httpClient` argument), you need to add `--cap-add=SYS_ADMIN` to the Docker options on Linux systems.
