### ISSUE TITLE
"Max redirect number exceeded" when running against Imperva Cloud WAF (Incapsula) protected web sites.

### ISSUE THREAD

**Issue by eguillotin** [wallarm/gotestwaf#57]
Hi,

I am trying to use the tool to test Imperva Cloud WAF protected web sites and keep having "Max redirect number exceeded" whatever the limit I set. Can you help me to figure out why it happens ? Thanks.

**Comment by manmolecular** [comment]
Hello!

This should be fixed now: https://github.com/wallarm/gotestwaf/pull/61
Please, update gotestwaf to the latest version.

**Comment by dnkolegov** [comment]
Please reopen if needed.
