### ISSUE TITLE
AWS WAF (Web ACL): "WAF was not detected"

### ISSUE THREAD

**Issue by guilhermeIO** [wallarm/gotestwaf#94]
I have a web app setup through AWS CloudFront + S3 + WAF.

When I run the command to test against the target:
```sh
sudo docker run -v ${PWD}/reports:/app/reports wallarm/gotestwaf --url=https://waf-protected-url.example
```

I get the following error output:
```
GOTESTWAF : 2021/10/29 19:32:09.692105 main.go:60: GoTestWAF unknown
GOTESTWAF : 2021/10/29 19:32:09.692670 main.go:70: Test cases loading started
GOTESTWAF : 2021/10/29 19:32:09.694009 main.go:77: Test cases loading finished
GOTESTWAF : 2021/10/29 19:32:09.694023 main.go:90: gRPC pre-check: IN PROGRESS
GOTESTWAF : 2021/10/29 19:32:12.695429 main.go:94: gRPC pre-check: connection is not available, reason: sending gRPC request: context deadline exceeded
GOTESTWAF : 2021/10/29 19:32:12.695483 main.go:104: Scanned URL: https://waf-protected-url.example
GOTESTWAF : 2021/10/29 19:32:13.244458 main.go:45: main error: WAF was not detected. Please use the '--blockStatusCode' or '--blockRegex' flags. Use '--help' for additional info.
```

> Adding `--blockStatusCode` or `--blockRegex` does not change the output for me.

----

When I access the Web ACL dashboard, **I can see the requests fired by _gotestwaf_ are being captured and blocked.**

Any insight into the issue would be very helpful.
Thank you!

**Comment by iambryancs** [comment]
@guilhermeIO try setting the `--skipWAFBlockCheck` option. This worked for me against a CloudFront endpoint with WAF configured.

**Comment by guilhermeIO** [comment]
@iambryancs Adding `--skipWAFBlockCheck` actually worked :tada:

As a side note, I see most test cases with status `200`, but the WAF shows the requests were actually blocked.

Anyway,  thanks a lot!

**Comment by RichardPerry** [comment]
Not fully related, but could any anybody explain how to fromat the regex so that they match something returned by the WAF, for example awselb/2.0 header
